### ISSUE TITLE
[Error] Windows 10 MiCreateImageFileMap.lmod V11 not me

### ISSUE THREAD

**Issue by L1B0** [eurecom-s3/loaders_modeling#2]
Hi, I test the win10 MiCreateImageFileMap.lmod by using a  64bits exe, which can run on win10.19041 correctly.
As well as the script outputs "Verification failed", which is not occured when I use 32-bits binary.
```
❯ python3 verify.py models/windows/10/MiCreateImageFileMap.lmod ../createprocess.exe 
2021-12-22 22:57:48 ubuntu modelLang.backends.python_backend[6579] CRITICAL Terminal condition V11 not met. Verification failed
```
I checked the Terminal condition V11, which is "optHdr.Magic == 0x10b", that means the binary must be 32-bits.

Is it an mistake? Or it just support 32-bits PE file by now. 
Thanks!

This is my test file, it just create a process named hello.exe.
[createprocess.zip](https://github.com/eurecom-s3/loaders-models/files/7767388/createprocess.zip)

**Comment by mpuzz** [comment]
Hi,
so far we only have models for the loaders of 32bit versions of windows.
These loaders only handle PE32 executables. As such, it's normal that the models reject PE32+ executables as invalid.

**Comment by L1B0** [comment]
Thanks for your reply:-)
